name: Apply Terraform

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: gabriellmb05/terraform-ci/.github/workflows/terraform.yaml@main
    with:
      working_directory: infra
      environment: prod
    secrets:
      aws_assume_role_arn: ${{ secrets.aws_assume_role_arn }}