name: TFLint
on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1
      
      - name: TFLint init
        run: tflint --recursive --init

      - name: Run TFLint
        run: tflint --recursive --config "$(pwd)/infra/.tflint.hcl"